src/article/urls.py
from django.conf.urls import url

from .views import(
        listArticle,
        getArticle,
        deleteArticle,
        updateArticle,
        createArticle,
        searchResult,
        searchResultInDetail,
        allArticle,
        )
"""
URL rooter for artical which include List, detail, update and create.
Detail achieve by Dynamic URL binding which pass primary_key as parameter to getArticle(),name can be bind by href.
"""
urlpatterns = [
    url(r'^$',listArticle,name = "articleList"),
    url(r'^(?P<pk>\d+)/$',getArticle,name="detail"),
    url(r'^(?P<pk>\d+)/delete/$',deleteArticle,name="delete"),
    # url(r'^(?P<pk>\d+)/edit/$',updateArticle,name="edit"),
    # url(r'^create/$',createArticle),
    url(r'^ways/$',allArticle,name="allArticle"),
    # ajax search
    url(r'^ajax/$',searchResult),
    url(r'^(?P<pk>\d+)/ajax/$',searchResultInDetail),
    url(r'^ways/ajax/$',searchResult),
]

src/blog/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

from article import views as art

urlpatterns = [
    #admin page URL Rooter
    url(r'^admin/', admin.site.urls),
    #index page URL Rooter
    url(r'^index/',include('article.urls',namespace='article')),
]

# separate django static and our owns, gether them by run commind
if settings.DEBUG:
    urlpatterns +=static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns +=static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/article/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.conf import settings

from django.db import models
from django.core.urlresolvers import reverse
# from django.contrib import messages

class PostManager(models.Manager):
    """docstring for PostManager. rewrite origin filter"""
    def all(self,*args,**kwargs):
        return super(PostManager,self).order_by("-UpdateTime")

"""
save image according user
"""
def upload_location(instance,filename):
    return "%s/%s" %(instance.User,filename)

class Tag(models.Model):
    """docstring forTag."""
    Id=models.AutoField(primary_key=True)
    Tags=models.CharField(max_length=1000,blank = False)
    def __str__(self):
        return str(self.Tags)

"""
Not only the models also the method of each model obj
"""
class Article(models.Model):
    """docstring ss Article."""
    User=models.ForeignKey(settings.AUTH_USER_MODEL,default=1)
    Id=models.AutoField(primary_key=True)
    Title=models.CharField(max_length=1000,blank = False)
    Counter=models.IntegerField(default=0)
    Image=models.ImageField(upload_to=upload_location,
                            null=False,
                            blank=False,
                            width_field='width_field',
                            height_field='height_field',)
    height_field=models.IntegerField(default=0)
    width_field=models.IntegerField(default=0)

    Publish=models.BooleanField(default=False)
    Content=models.TextField()
    UpdateTime=models.DateTimeField(auto_now_add=False,auto_now=True)
    Build=models.DateTimeField(auto_now_add=True,auto_now=False)
    Tags = models.ManyToManyField(Tag,through='TagsArticle')

    #objects is build in by django, like Article.objects.all()
    objects=PostManager()
    def __str__(self):
        """
        return  exercise Description
        """
        return str(self.Title)
    #get URL dynamic also can ues URL "article:detail" pk=obj.id
    def get_absolute_url(self):
        return reverse("article:detail",kwargs={"pk":self.Id})

class TagsArticle(models.Model):
    Article=models.ForeignKey(Article)
    Tags=models.ForeignKey(Tag)

src/article/forms.py
from django import forms
from .models import Article
from pagedown.widgets import PagedownWidget
from pagedown.widgets import AdminPagedownWidget

"""
form for admin page post artical
"""
class PostForm(forms.ModelForm):
    Content=forms.CharField(widget=AdminPagedownWidget())
    class Meta:
        """docstring Meta."""
        model=Article
        fields=[
            "Title",
            "Content",
            "Publish",
            "Image"
        ]

src/article/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.http import HttpResponse,HttpResponseRedirect,Http404
from django.shortcuts import render,get_object_or_404,redirect,get_list_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from .models import Article,TagsArticle,Tag
from .forms import PostForm

# Create your views here.
"""
query all artical which published and paginator
"""
def allArticle(request):
    title='Way to Master'
    limit=7
    queryTag=request.GET.get("qtag")
    if queryTag=='all':
        quearyset=Article.objects.all()
    if not request.user.is_staff or not request.user.is_superuser:
        quearyset=Article.objects.filter(Publish=True).order_by("-UpdateTime")
    else:
        quearyset=Article.objects.all()

    if queryTag:
        # quearyset=quearyset.filter(Title__icontains=queryTag)
        if queryTag=='all':
            quearyset=Article.objects.filter(Publish=True).order_by("-UpdateTime")
        else:
            quearyset=getTagArticle(queryTag)

    tagset=Tag.objects.all()
    paginator = Paginator(quearyset, limit) # Show 2 contacts per page
    page = request.GET.get('page')
    try:
        contacts = paginator.page(page)
    except PageNotAnInteger:
        contacts=paginator.page(1)
    except EmptyPage:
        contacts=paginator.page(paginator.num_pages)

    TagArray=getTags(contacts)
    rows=zip(contacts,TagArray)
    context={
    	# "form":form,
        "title":title,
        "objects_list":contacts,
        "rows":rows,
        "tagset":tagset
    }
    return render(request,"article.html",context)

"""
return all related article with one tag
"""
def getTagArticle(tag):
    allArticle=[]
    tagObj=get_object_or_404(Tag,Tags=tag)
    articles=get_list_or_404(TagsArticle,Tags=tagObj.Id)
    for i in range(len(articles)):
        allArticle.append(articles[i].Article)
    return allArticle
"""
return tages for each article，add [] if tag not exist.
"""
def getTags(array):
    AllTags=[]
    for i in array:
        current=[]
        # tags=get_list_or_404(TagsArticle,Article=i.Id)
        tags=list(TagsArticle.objects.filter(Article=i.Id))
        if tags:
            for i in range(len(tags)):
                current.append(tags[i].Tags)
        else:
            current.append([])
        AllTags.append(current)
    return AllTags


"""
query first 7 artical which published and return it to sidebar if not superuser,
else return all artical.
"""
def listArticle(request):
    limit=7
    if not request.user.is_staff or not request.user.is_superuser:
        quearyset=Article.objects.filter(Publish=True).order_by("-UpdateTime")[:limit]
    else:
        quearyset=Article.objects.all()
    context={
        "objects_list":quearyset,
    }
    return render(request,"postList.html",context)

"""
post an articals（not use change post artical in admin page）
"""
def createArticle(request):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    form=PostForm(request.POST or None,request.FILES or None)
    if form.is_valid():
        instance=form.save(commit=False)
        # print form.cleaned_data.get("Content")
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())

    context={
        "form":form,
        "from":"Create",
    }
    return render(request,"post.html",context)

"""
show detail of artiacal
"""
def getArticle(request,pk):
    obj=get_object_or_404(Article,Id=pk)
    tags=getTag(obj)
    if obj:
        obj.Counter+=1
        obj.save()
    context={
        "objects":obj,
        "tags":tags
    }
    return render(request,"detail.html",context)

def getTag(obj):
    current=[]
    # tags=get_list_or_404(TagsArticle,Article=i.Id)
    tags=list(TagsArticle.objects.filter(Article=obj.Id))
    if tags:
        for i in range(len(tags)):
            current.append(tags[i].Tags)
    else:
        current.append([])
    return current

"""
delete articals
"""
def deleteArticle(request,pk):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance=get_object_or_404(Article,Id=pk)
    instance.delete()

    return redirect("article:articleList")

"""
edit artical (not use change, edit artical in admin page）
"""
def updateArticle(request,pk):
    if not request.user.is_staff or not request.user.is_superuser:
        raise Http404
    instance=get_object_or_404(Article,Id=pk)
    form=PostForm(request.POST or None,request.FILES or None,instance=instance)
    if form.is_valid():
        instance=form.save(commit=False)
        instance.save()
        return HttpResponseRedirect(instance.get_absolute_url())
    context={
        "form":form,
        "from":"Edit",
    }
    return render(request,"post.html",context)

"""
Ajax search result
"""


def searchResultInDetail(request, pk):
    if request.method=='GET':
        search_by=request.GET['search_by']
        if search_by is not None and search_by != u"":
            search_by=request.GET['search_by']
            statuss = Article.objects.filter(Content__contains = search_by)
        else:
            statuss = []
        context={
            'statuss':statuss,
            'searchText':search_by
        }
        return render(request, 'sideBarSearch.html', context)

def searchResult(request):
    if request.method=='GET':
        search_by=request.GET['search_by']
        if search_by is not None and search_by != u"":
            search_by=request.GET['search_by']
            statuss = Article.objects.filter(Content__contains = search_by)
        else:
            statuss = []
        context={
            'statuss':statuss,
            'searchText':search_by
        }
        return render(request, 'sideBarSearch.html', context)

src/templates/article.html
{%extends 'base.html' %}
{% load tz %}

{% load static %}

{%block pagetitle%}{{title}}| {{block.super}}{%endblock pagetitle%}

{%block css%}
<link rel="stylesheet" type="text/css" href="{% static 'css/article.css' %}">
{%endblock css%}

{%block intro%}
<div class="intro-detail">
    <h1 >{{title}}</h1>
</div>
{%endblock intro%}

{%block body%}
  <div class="container">
    <div class="row">
      <div class="col-lg-10" >
      {%for row in rows%}
            <h2>{{row.0.Title}}</h2>
            <div class="tags">
            {%for tag in row.1%}
              {%if tag%}
                <div class="tag">
                  {{tag.Tags}}
                </div>
              {%endif%}
            {%endfor%}
            </div>
            <p class="new-font-color">{{row.0.User}} | {{row.0.UpdateTime|localtime|date:'M d, Y'}}</p>
            <p class="content-markdown">{{row.0.Content|truncatechars:140}}</p>
            <a class="news-h1" href="{%url "article:detail" pk=row.0.Id %}">Read More</a>
            <hr style="border-top: 2px solid #00000080;">
        {%endfor%}
        </div>

        <div class="col-lg-2">
          <p><a class="filter-tag" href="/index/ways/?qtag=all">All</a></p>
          {%for tag in tagset%}
            <p><a class="filter-tag" href="/index/ways/?qtag={{tag}}">{{tag}}</a></p>
          {%endfor%}
        </div>
      </div>
  </div>
<!-- start pagination -->
<nav aria-label="..." class="pagenav" style="text-align: center;">
  <div class="pagination">
      {% if objects_list.has_previous %}
        <li class="page-item"><a href="?page=1">&laquo; first</a></li>
        <li class="page-item disabled">
          <a class="page-link" href="?page={{ objects_list.previous_page_number }}">previous</a>
        </li>
        <li class="page-item">
            <a href="?page={{ objects_list.previous_page_number }}">{{ objects_list.previous_page_number }}</a>
        </li>
      {% endif %}

      <li class="page-item active">
        <a class="page-link" href="#">{{ objects_list.number }} <span class="sr-only">(current)</span></a>
      </li>

      {% if objects_list.has_next %}
      <li class="page-item">
          <a href="?page={{ objects_list.next_page_number }}">{{ objects_list.next_page_number }}</a>
      </li>
      <li class="page-item">
          <a href="?page={{ objects_list.next_page_number }}">next</a>
       </li>
       <li class="page-item">
          <a href="?page={{ objects_list.paginator.num_pages }}">last &raquo;</a>
        </li>
      {% endif %}
  </div>
</nav>
<!-- end pagination -->
{%endblock body%}
{%block jsAfterDOM%}
{%endblock jsAfterDOM%}

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <!--for media screen  -->
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>
      {%block pagetitle%}Panchy{%endblock pagetitle%}
    </title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    {%block css%}
    {%endblock css%}

    {%block head_extra%}
    {%endblock head_extra%}

  </head>
  <body>
    <!-- facebook comment api -->
    <div id="fb-root"></div>
    <script>(function(d, s, id) {
      var js, fjs = d.getElementsByTagName(s)[0];
      if (d.getElementById(id)) return;
      js = d.createElement(s); js.id = id;
      js.src = 'https://connect.facebook.net/zh_CN/sdk.js#xfbml=1&version=v3.0&appId=174874923156471&autoLogAppEvents=1';
      fjs.parentNode.insertBefore(js, fjs);
    }(document, 'script', 'facebook-jssdk'));</script>
    <!--end facebook comment api -->

    <div class="wrapper">
      <nav id="sidebar">
        <!-- Sidebar Header -->
        <div class="sidebar-form">
          <form class="navbar-form navbar-left">
            <div class="form-group">
              <input type="text" class="form-control" style="width: 100%;" id="search" placeholder="Search">
              <!-- <input type="image" src="{% static 'image/search.png' %}" value=""> -->
            </div>
            <!-- <button type="submit" class="btn btn-default">Submit</button> -->
          </form>
        </div>
          <!-- Sidebar Links -->
          <div id="search-result">
            {%block sideBarSearch%}
            {%endblock sideBarSearch%}
          </div>
          <div class="sidebar-footer">
            <p>@2018 Panchy</p>
          </div>
      </nav>
      <div class="bg">
        <div class="inner">
          <nav class="navbar navbar-default" id="navbar">
            <div class="container-fluid">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                  <span class="sr-only">Toggle navigation</span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                  <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="#">PANCHY</a>
              </div>
              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                  <li><a class="nav-a" href="{% url 'article:articleList' %}">Home</a></li>
                  <li><a class="nav-a" href="{%url 'article:allArticle'%}">Ways</a></li>
                  <li><a class="nav-a" href="mailto:qpang@ualberta.ca?Subject=Hello">Email</a></li>
                </ul>
              </div><!-- /.navbar-collapse -->
            </div><!-- /.container-fluid -->
            <div class="side-btn" style="display:inline">
              <a type="button" class="nav-side-btn" id="sidebarCollapse" >
                <img class="nav-side-btn-img" src="{% static 'image/chevron-right-d.png' %}" alt="">
              </a>
            </div>
          </nav>
          {%block intro%}
          <div class="intro-text">
            <h1 id="intro-title">Developer</h1>
            <hr style="width: 30%;float: left;">
            <br>
            <p id="intro-text">Experienced data driving web application developer, who loves agile development and newest technologies. With 1+ years of experience in Android and web application. Also having background knowledge on machine learning and game AI.</p>
            <div class="play-btn">
              <a href="https://github.com/panchyo0" type="button" name="button">
                <img id="play" src="{% static 'image/github.png' %}" alt="">
              </a>
            </div>
          </div>
          {%endblock intro%}
        </div><!--end inner  -->
        <div class="container star-body">
          {%block body%}
          {%endblock body%}
        </div>
      </div><!--end bg  -->
    </div><!--end wrapper  -->


  </body>

  <script src="https://code.jquery.com/jquery-3.3.1.js" integrity="sha256-2Kok7MbOyxpgUVvAk/HJ2jigOSYS2auK4Pfzbm7uH60=" crossorigin="anonymous"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
  <script src="{% static 'js/base.js' %}"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.19/marked.min.js"></script>
  {%block jsAfterDOM%}
  {%endblock jsAfterDOM%}
</html>

src/templates/detail.html
{%extends 'base.html' %}
{% load tz %}

{% load static %}

{%block pagetitle%}{{objects.Title}} | {{block.super}}{%endblock pagetitle%}

{%block css%}
<link rel="stylesheet" type="text/css" href="{% static 'css/detail.css' %}">
{%endblock css%}

{%block intro%}
<div class="intro-detail">
    <h1 >{{objects.Title}}</h1>
    <h4 id='time-auth'>{{objects.Build|localtime|date:'M d, Y'}} by {{objects.User}}</h4>
    {%if tags%}
      {%for tag in tags%}
      <a class="intro-tag">{{tag.Tags}}</a>
      {%endfor%}
    {%endif%}

    {%if user.is_authenticated%}
      <p class="btn btn-default">{{objects.Counter}} Reads</p>
    {%endif%}
</div>
{%endblock intro%}

{%block body%}
  <style media="screen">
    .bg{
        /* The image used */
        background-image: url({{objects.Image.url}});
    }
  </style>
<div class="container" style="padding-right: 10%;padding-left: 10%;margin-bottom: 7%;">
  {%if not objects.Publish%}
  <p>Draft</p>
  {%endif%}

  <p class="content-markdown">{{objects.Content}}</p>
  <div class="fb-comments" data-href="" data-numposts="5"></div>
</div>
{%endblock body%}

{%block jsAfterDOM%}
{%endblock jsAfterDOM%}

src/templates/post.html
{%extends 'base.html' %}
<!-- {% load static %} -->

{%block pagetitle%}{{from}}{%endblock pagetitle%}
{%block css%}
<link rel="stylesheet" type="text/css" href="{% static 'css/post.css' %}">
{{ form.media }}
{%endblock css%}



{%block intro%}

<div class="intro row">
  <div class="col-lg-6">
    <p id="flag">{{from}}</p>
    <form method="post" enctype="multipart/form-data"> {%csrf_token%}
      {{form.as_p}}
      <button type="submit" id="sub_form" class="btn btn-default">Submit</button>
    </form>
  </div>

  <div class="col-lg-6">
    {{form.media}}
  </div>
</div>
{%endblock intro%}

{%block body%}
<!-- <div class="">
  <p id="flag">{{from}}</p>
  <form class="" action="" method="post" enctype="multipart/form-data"> {%csrf_token%}
    {{form.as_p}}
    <button type="submit" id="sub_form">Submit</button>
  </form>
</div> -->
{%endblock body%}
{%block jsAfterDOM%}
<!-- <script src="https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.19/marked.min.js"></script> -->
<script src="{% static 'js/post.js' %}"></script>
{%endblock jsAfterDOM%}

src/templates/postList.html
{%extends 'base.html' %}

{% load static %}
{% load tz %}

{%block css%}
<link rel="stylesheet" type="text/css" href="{% static 'css/postList.css' %}">
{%endblock css%}

{%block sideBarSearch%}
<div class="">
  <h3 class="title">Recent Post</h3>
  {%for obj in objects_list|slice:":10"%}
  <!-- <div class="col-md-4"> -->
  <hr>
    <div class="thumbnail">

      <a href="{%url "article:detail" pk=obj.Id %}">
        <!-- <img src="/w3images/lights.jpg" alt="Lights" style="width:100%"> -->
        {%if obj.Image%}
        <div class="">
          <img src="{{obj.Image.url}}" class="img-responsive">
          <div class="no-shadow">
          </div>
        </div>
        {%endif%}
        <div class="caption post-text">
          <p class="time-color" id="article-date">{{obj.Build|localtime|date:'M d, Y'}}</p>
          <h4 id="article-title">{{obj.Title}}</h4>
          <p class="content-markdown" id="article-content">{{obj.Content|truncatechars:70}}</p>
        </div>
      </a>
  </div>
  {%endfor%}
</div>

{%endblock sideBarSearch%}

{%block body%}


{%endblock body%}
{%block jsAfterDOM%}
<script src="{% static 'js/postList.js' %}"></script>
{%endblock jsAfterDOM%}

src/templates/sideBarSearch.html
{%block sideBarSearch%}
{%if statuss%}
  <p class="sidebar-text-styly">Found "{{searchText}}" In:</p>
  <hr>
  {%for article in statuss%}
  <div class="inline">
    <!-- <img src="{{article.Image.url}}" class="img-responsive" alt=""> -->
    <img src="/static/image/search.png" alt="" class="img-responsive search-img">
    <a href="{%url "article:detail" pk=article.Id %}" class="sidebar-text-styly">
      {{article.Title}}
    </a>
  </div>
    <hr>
  {%endfor%}
{%else%}
  <p class="sidebar-text-styly">Nothing related "{{searchText}}" found.</p>
{%endif%}

{%endblock sideBarSearch%}